### ISSUE TITLE
currentHashingTask_update invalid hashing size triggered

### ISSUE THREAD

**Issue by OmegaPhil** [OmegaPhil/animecheck#28]
```
     84% 356.16MB/Sec
ERROR: Failed to crc32 hash the file '/mnt/Storage_6/KVIrc Download/[FroZen-EviL]_Yawara_-_01_[DVD][0A533918].mkv':

currentHashingTask_update was informed that 65536B had been hashed, however only 34992B remains to hash

Traceback (most recent call last):
  File "/mnt/Storage_1/Programming/Python/animecheck/animecheck.py", line 979, in hash_files
    checksum = crc32_checksum(fileToHash)
  File "/mnt/Storage_1/Programming/Python/animecheck/animecheck.py", line 121, in crc32_checksum
    hashedSoFar=done)
  File "/mnt/Storage_1/Programming/Python/animecheck/animecheck.py", line 776, in currentHashingTask_update
    currentHashingTask['dataToHash']))
Exception: currentHashingTask_update was informed that 65536B had been hashed, however only 34992B remains to hash


Hashing task complete: 1 file, 0 not found, 1 other error, 0 corrupt, 0 no hash, 0 hashed successfully
Started 04/05/14 11:20:27, finished 04/05/14 11:20:27, elapsed 0:00:00.618919, 211.69MB hashed (342.03MB/Sec)
```

This is actually consistent! Finally something to fight this with.

**Comment by OmegaPhil** [comment]
I have just had a consistent example of this when accidentally hashing a file that was being written to. Worth improving the error reporting at least.
